wifi:
  ssid: VierkantFolstar
  password: !secret wifi_password

# Enable logging.
logger:

# Enable Home Assistant API.
api:

# Enable over-the-air updates.
ota:

web_server:
  port: 80

# Sensors with general information.
sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: $devicename WiFi Signal
    update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: $devicename ESPHome Version
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID

switch:
  - platform: restart
    name: $devicename Restart
