---
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: doorsensor

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: Voordeur
    device_class: window

sensor:
  - platform: pulse_counter
    pin:
      number: D5
    update_interval : 6s
    name: "water pulse"
    id: water_pulse

  - platform: pulse_meter
    pin:
      number: D5
    name: "Water Pulse Meter"
    unit_of_measurement: "liter/min"
    icon: "mdi:water"
    total:
      name: "Water Meter Total"
      unit_of_measurement: "m³"
      id: water_meter_total
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - multiply: 0.001

  - platform: template
    name: "Water Usage Liter"
    id: water_flow_rate
    accuracy_decimals: 1
    unit_of_measurement: "l/min"
    icon: "mdi:water"
    lambda: return (id(water_pulse).state * 10);
    update_interval: 6s

button:
  - platform: template
    name: "Alles uit"
    on_press:
      - light.turn_off: onder
      - light.turn_off: midden
      - light.turn_off: boven
  - platform: template
    name: "Vlag"
    on_press:
      - light.turn_on:
          id: neopixel
          red: 100%
          green: 65%
          blue: 0%
          brightness: 100%
          transition_length: 5s
      - delay: 10s
      - light.turn_off: onder
      - light.turn_off: midden
      - light.turn_off: boven
      - light.turn_on:
          id: onder
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 1s
      - delay: 5s
      - light.turn_on:
          id: onder
          red: 100%
          green: 100%
          blue: 100%
          brightness: 75%
          transition_length: 1s
      - light.turn_on:
          id: midden
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 1s
      - delay: 5s
      - light.turn_on:
          id: boven
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 1s
      - light.turn_on:
          id: midden
          red: 100%
          green: 100%
          blue: 100%
          brightness: 75%
          transition_length: 1s
      - light.turn_on:
          id: onder
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
          transition_length: 1s

light:
  - platform: partition
    name: "Boven"
    id: boven
    segments:
      - id: neopixel
        from: 2
        to: 2
    effects: !include { file: light-effects.yaml }

  - platform: partition
    id: midden
    name: "Midden"
    segments:
      - id: neopixel
        from: 1
        to: 1
    effects: !include { file: light-effects.yaml }

  - platform: partition
    id: onder
    name: "Onder"
    segments:
      - id: neopixel
        from: 0
        to: 0
    effects: !include { file: light-effects.yaml }

  - platform: neopixelbus
    id: neopixel
    type: RGB
    variant: WS2812
    pin: D2
    num_leds: 3
    name: "NeoPixel Light"
    effects: !include { file: light-effects.yaml }

<<: !include common.yaml
