---
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: doorsensor

globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: Voordeur
    device_class: window
  - platform: gpio
    id: doorbell_button
    name: Deurbel knop
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: true
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: relay

# Exposed switches.
switch:
  # Switch to turn on/off the chime.
  - platform: gpio
    id: relay
    name: Deurbel gong
    pin:
      number: D2

  - platform: template
    name: Deurbel actief
    id: chime_active
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);

sensor:
  - platform: pulse_meter
    pin:
      number: D3
    name: "Watergebruik huidig"
    id: water_flow_rate
    accuracy_decimals: 1
    unit_of_measurement: "l/min"
    icon: "mdi:water"
    total:
      name: "Watergebruik totaal"
      unit_of_measurement: "L"
      device_class: water
      state_class: total_increasing
      accuracy_decimals: 1
      icon: "mdi:water"

button:
  - platform: template
    name: "Deurbel: 1x kort"
    on_press:
      - switch.turn_on: relay
      - delay: 300ms
      - switch.turn_off: relay
  - platform: template
    name: "Licht uit"
    on_press:
      - light.turn_off: onder
      - light.turn_off: midden
      - light.turn_off: boven
  - platform: template
    name: "Licht: Vlag"
    on_press:
      - light.turn_on:
          id: neopixel
          red: 100%
          green: 65%
          blue: 0%
          brightness: 100%
          transition_length: 5s
      - delay: 10s
      - light.turn_off: onder
      - light.turn_off: midden
      - light.turn_off: boven
      - light.turn_on:
          id: onder
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 1s
      - delay: 5s
      - light.turn_on:
          id: onder
          red: 100%
          green: 100%
          blue: 100%
          brightness: 75%
          transition_length: 1s
      - light.turn_on:
          id: midden
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 1s
      - delay: 5s
      - light.turn_on:
          id: boven
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 1s
      - light.turn_on:
          id: midden
          red: 100%
          green: 100%
          blue: 100%
          brightness: 75%
          transition_length: 1s
      - light.turn_on:
          id: onder
          red: 0%
          green: 0%
          blue: 100%
          brightness: 100%
          transition_length: 1s

light:
  - platform: partition
    name: "Licht Boven"
    id: boven
    segments:
      - id: neopixel
        from: 2
        to: 2
    effects: !include { file: light-effects.yaml }

  - platform: partition
    id: midden
    name: "Licht Midden"
    segments:
      - id: neopixel
        from: 1
        to: 1
    effects: !include { file: light-effects.yaml }

  - platform: partition
    id: onder
    name: "Licht Onder"
    segments:
      - id: neopixel
        from: 0
        to: 0
    effects: !include { file: light-effects.yaml }

  - platform: neopixelbus
    id: neopixel
    type: RGB
    variant: WS2812
    pin: D4
    internal: true
    num_leds: 3
    name: "NeoPixel Light"
    effects: !include { file: light-effects.yaml }

<<: !include common.yaml
