---
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: garage

switch:
  - platform: gpio
    id: relay
    name: Garagedeur openen
    pin:
      number: D1
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: Garagedeur volledig dicht
    id: garagedeur_volledig_dicht
    device_class: door
    internal: true
  - platform: gpio
    id: garage_tussendeur
    pin:
      number: D3
      mode: INPUT_PULLUP
    name: Tussendeur
    device_class: door
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: Garagedeur volledig geopend
    id: garagedeur_volledig_open
    device_class: door
    internal: true

  - platform: gpio
    id: garage_motion
    pin:
      number: D5
      mode: INPUT_PULLUP
    filters:
      - delayed_off: 10s
    name: "PIR Sensor"
    device_class: motion

cover:
  - platform: template
    name: "Garagedeur"
    device_class: garage

    lambda: |-
      if (id(garagedeur_volledig_dicht).state == false) {
        return COVER_CLOSED;
      } else if (id(garagedeur_volledig_open).state == false) {
        return COVER_OPEN;
      } else {
        return COVER_OPERATION_OPENING;
      }

    open_action:
      - lambda: |-
          if (!id(garage_tussendeur).state) {
            id(relay).turn_on();
          }

    close_action:
      - lambda: |-
          if (!id(garage_tussendeur).state) {
            id(relay).turn_on();
          }

    stop_action:
      - lambda: |-
          if (!id(garage_tussendeur).state) {
            id(relay).turn_on();
          }

<<: !include common.yaml
