---
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: garage

# Exposed switches.
switch:
  - platform: gpio
    id: relay
    name: Garagedeur openen
    pin:
      number: D1
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: relay

# Binary sensor representing the
# Garagedeur button push.
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: Garagedeur
    id: garagedeur_volledig_dicht
    filters:
      - delayed_on_off: 1000ms
    device_class: window
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
    name: Tussendeur
    filters:
      - delayed_on_off: 1000ms
    device_class: window
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: Garagedeur geopend
    id: garagedeur_volledig_open
    filters:
      - delayed_on_off: 1000ms
    device_class: door

  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 1000ms
    name: "PIR Sensor"
    device_class: motion

  - platform: template
    id: garagedeur_moving
    name: Garagedeur In beweging
    lambda: |-
      if ((id(garagedeur_volledig_open).state) and (id(garagedeur_volledig_dicht).state)) {
        return true;
      } else {
        return false;
      }

<<: !include common.yaml
