---
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: keukentje

select:
  - platform: template
    name: "Licht-effect spotjes"
    optimistic: true
    options:
      - Regenboog
      - None
    initial_option: None
    id: licht_effect_spotjes
    on_value:
      then:
        light.control:
          id: keuken_spotjes
          effect: !lambda return id(licht_effect_spotjes).state;

binary_sensor:
  # Kookplaat
  - platform: gpio
    id: keuken_knop1
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    name: Knop 1
    on_click:
      - max_length: 500ms
        then:
          - if:
              condition:
                light.is_on: keuken_spotjes
              then:
                - select.next: licht_effect_spotjes
              else:
                - light.turn_on: keuken_spotjes
      - min_length: 500ms
        max_length: 1000ms
        then:
          - light.turn_off: keuken_spotjes
          - light.turn_off: keuken_magnetron_licht
          - light.turn_off: keuken_oven_licht

  - platform: gpio
    id: keuken_knop2
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    name: Knop 2
    on_press:
      then:
        - light.turn_on: keuken_spotjes
        - if:
            condition:
              light.is_on: keuken_kookplaat
            then:
              - light.turn_off: keuken_kookplaat
            else:
              - light.turn_on:
                  id: keuken_kookplaat
                  brightness: 100%
                  red: 100%

  # Magnetron
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: Magnetron deurtje
    device_class: window
    on_press:
      then:
        - light.turn_on: keuken_spotjes
        - light.turn_on:
            id: keuken_magnetron_licht
            red: 100%
            green: 100%
            blue: 100%
            brightness: 100%
    on_release:
      then:
        - light.control:
            id: keuken_magnetron_licht
            state: on
            brightness: 75%
            effect: none
        - delay: 3s
        - light.control:
            id: keuken_magnetron_licht
            state: on
            effect: Vuurwerk
            brightness: 100%
        - delay: 3s
        - light.control:
            id: keuken_magnetron_licht
            state: on
            effect: Groen knipperend
            brightness: 100%
        - delay: 3s
        - light.control:
            id: keuken_magnetron_licht
            brightness: 50%
            effect: none

  # Oven
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: Keuken oven
    device_class: door
    on_press:
      then:
        - light.turn_on: keuken_spotjes
        - light.turn_on:
            id: keuken_oven_licht
            red: 100%
            green: 100%
            blue: 100%
            brightness: 100%
    on_release:
      then:
        - light.control:
            state: on
            id: keuken_oven_licht
            red: 100%
            green: 100%
            blue: 100%
            brightness: 20%
        - light.control:
            id: keuken_oven_licht
            red: 100%
            green: 0%
            blue: 0%
            brightness: 100%
            transition_length: 10s

light:
  - platform: partition
    id: keuken_oven_licht
    icon: mdi:stove
    name: "Oven"
    segments:
      - id: keuken_neopixel
        from: 0
        to: 0
    effects: !include { file: light-effects.yaml }

  - platform: partition
    name: "Keuken spotjes"
    id: keuken_spotjes
    icon: mdi:led-strip-variant
    segments:
      - id: keuken_neopixel
        from: 1
        to: 19
    effects: !include { file: light-effects.yaml }

  - platform: partition
    name: "Magnetron"
    id: keuken_magnetron_licht
    icon: mdi:microwave
    segments:
      - id: keuken_neopixel
        from: 20
        to: 20
    effects: !include { file: light-effects.yaml }

  - platform: neopixelbus
    id: keuken_neopixel
    type: GRB
    internal: true
    variant: SK6812
    pin: D4
    num_leds: 21

    # Kookplaat
  - platform: neopixelbus
    id: keuken_kookplaat
    type: RGB
    icon: mdi:gas-burner
    variant: WS2812
    pin: D6
    num_leds: 6

<<: !include common.yaml
